services:
  frontend:
    build: ./front
    depends_on:
      - backend
    volumes:
      - ./front:/app
    ports:
      - 3000:3000
  backend:
    build: ./back
    depends_on:
      - mongo
    volumes:
      - ./back:/app
    ports:
      - 4000:4000
  mongo:
    container_name: mongo
    image: mongo
    ports:
      - 27017:27017
    volumes:
      - mongodb:/data/db

  mailhog:
    image: mailhog/mailhog
    logging:
      driver: 'none'  # disable saving logs
    ports:
      - 1025:1025 # smtp server
      - 8025:8025 # web ui

volumes:
  mongodb: